### PR TITLE
Use yum

### PR DESCRIPTION
**Pull request by matyasselmeci**
dnf is not available on el7. On el9, yum is an alias to dnf.

### CODE REVIEW

**Comment by brianhlin** [comment]
Womp womp

```
9.772 --> Finished Dependency Resolution
9.772 Error: Package: ganglia-gmetad-3.7.2-40.el7.x86_64 (epel)
9.772            Requires: librrd.so.4()(64bit)
```

**Comment by matyasselmeci** [comment]
womp womp indeed. OSG's version of rrdtool, which provides librrd.so.8, is what's getting installed.
Did the el7 image ever work? Maybe we should exclude el7 from this one's build matrix?

**Comment by brianhlin** [comment]
> Maybe we should exclude el7 from this one's build matrix?

We don't have that ability right now :(. I really want to implement per image configs but otherwise everything is driven by https://github.com/opensciencegrid/images/blob/main/.github/workflows/build-containers.yml#L88-L98

> Did the el7 image ever work? 

Nope because we weren't building them. This image inherits from `ospool-cm` and that got changed from EL8 -> EL7 for 3.6 and EL9 for OSG 23 (the defaults for this repo)

**Comment by matyasselmeci** [comment]
So what's your suggestion? I'd hate to forget about this and have to debug later to come to the same conclusion... add near the top
```
RUN if grep 'release 7' /etc/redhat-release; then echo "ERROR: This package does not build on EL 7 because librrd.so.4 is not available"; exit 1; fi
```
?

**Comment by brianhlin** [comment]
Yeah, something like that is fine by me for now. Does exiting 1 in a `RUN` layer actually bail on the build?

**Comment by matyasselmeci** [comment]
Sure. RUN steps are run with `sh -e` so any non-zero return code will cause a failure.

**Comment by matyasselmeci** [comment]
I'll close this PR and make a separate PR with the bailout.

**Comment by matyasselmeci** [comment]
hang on, I can just edit the osg* repos on disk to add
```
exclude=*rrd*
```

**Comment by matyasselmeci** [comment]
Looks like `main` switched to OSG 23 which solves this problem in a different way I guess :)

Closing.

**Pull request closed without merging**
