### PR TITLE
vo-frontend: update EL8 3.5 repos (SOFTWARE-5078)

### PR DESCRIPTION
**Pull request by brianhlin**

### CODE REVIEW

**Comment by rynge** [comment]
Under EL8/3.5, I see glideinwms-vofrontend-standalone under osg-development. Are we waiting for it to go to osg-contrib?

**Comment by brianhlin** [comment]
Good catch! https://opensciencegrid.atlassian.net/browse/SOFTWARE-5084

**Comment by edquist** [comment]
@brianhlin, what is your goal here?  What information do you care about / want to see?

(Jumping in, i don't feel like i have enough context...)

Is it possible that you are actually interested in the diff between your PR head vs the PR base _commit_, rather than vs the main branch?  I don't know off hand if there is a `GITHUB_...` var with that commit info.  Presumably it'd be the same as a git merge-base of your PR head and the PR target branch (ie master/main).  You could then do a diff of the merge-base vs your PR head.

You could take it a step further and create a local merge commit, to ensure things are up to date, and then do your diff.  (That local commit would presumably then get discarded, but at least you can see what it would have looked like if the PR were up to date.)  Does not work if there are merge conflicts.

Otherwise, `git diff --summary` specifically names the files that are created/deleted, but it doesn't tell you about the ones that are simply changed, so maybe that's not helpful.

**Comment by brianhlin** [comment]
@edquist I misread your comment the first time around; I bet comparing vs the base commit would work! It doesn't look like GitHub provides an env var for it.

@matyasselmeci I added what amounts to a check for image root dir existence to handle this edge case. I can submit a different PR to add some suspenders with Carl's suggestion

**Review by matyasselmeci — APPROVED** [review]
If you have tested the find/cut/xargs/whatever voodoo then I am fine with it.

**Pull request merged**
