### PR TITLE
add init script to factory to force SHA1

### PR DESCRIPTION
**Pull request by jdost321**

### CODE REVIEW

**Comment by matyasselmeci** [comment]
We take care of this in the software-base image: if you launch the image with the environment variable `ENABLE_SHA1=YES` then it does exactly this.

**Comment by jdost321** [comment]
How do I set ENABLE_SHA1=YES then for the k8s factory?

**Comment by matyasselmeci** [comment]
In the env section for the container in the deployment. So add
```
- name: ENABLE_SHA1
  value: YES
```
in tiger-osg-config under `manifests/base/gwms-factory/deployment.yaml`, here
https://github.com/opensciencegrid/tiger-osg-config/blob/0048feca1931a9933342617ecfea1ee7a60c117a/manifests/base/gwms-factory/deployment.yaml#L47

**Comment by matyasselmeci** [comment]
or https://github.com/opensciencegrid/tiger-osg-config/blob/0048feca1931a9933342617ecfea1ee7a60c117a/manifests/development/gwms-factory/patch-deployment.yaml#L10 for the devel factory and https://github.com/opensciencegrid/tiger-osg-config/blob/0048feca1931a9933342617ecfea1ee7a60c117a/manifests/production/gwms-factory/patch-deployment.yaml#L10 for the prod factory

**Comment by jdost321** [comment]
great thanks. I forgot we're already setting some vars that way. I'll close this one then.

Jeff

**Pull request closed without merging**
