### PR TITLE
osgstorage-redirector: Move from EL7 to EL8

### PR DESCRIPTION
**Pull request by jthiltges**
Moving to EL9 would add OpenSSL 3, which needs a bit more care. Moving to EL8 would be a good intermediate step.

### CODE REVIEW

**Review by brianhlin — APPROVED** [review]
Fine by me! Feel free to merge when you're ready for it, or lmk if you can't merge (though I'll want to merge this soon to get #149 in)

**Comment by brianhlin** [comment]
@jthiltges I think what you had would work better if you want to move the container over to EL8: since the build action in #149 specifies the `base_os`, it'll override your `BASE_OS=el8` default build arg

**Comment by jthiltges** [comment]
Oof. Thanks much for the heads up. That's a non-intuitive result.

**Comment by brianhlin** [comment]
Yeah, it's not great it but I'm too nervous to mass move all these images to EL8/EL9 across OSG 3.6 + 23. Unfortunately, the current GHA build mechanism doesn't necessarily allow for per image controls just yet but I think it's feasible!

**Pull request merged**
