### PR TITLE
Al9 factory

### PR DESCRIPTION
**Pull request by jdost321**

### CODE REVIEW

**Comment by jdost321** [comment]
@brianhlin @jthiltges I am guessing I'm doing something wrong to get an al9  factory to build any ideas?

**Comment by brianhlin** [comment]
Failure is here: https://github.com/opensciencegrid/images/actions/runs/6266441370/job/17017439775?pr=148#step:2:792. I think we need to enable the CRB repo in the base

(I think you'll get this for free with OSG 23 and #149 btw)

**Comment by jthiltges** [comment]
On EL9, in addition to EPEL, looks like we'll need the CodeReady Builder (CRB) repo enabled:
```
dnf config-manager --set-enabled crb
```

**Comment by brianhlin** [comment]
Ah, we actually already do this but we don't ship a `3.6-al9-release` tag, we just ship `3.6-el9-release` which is based on AL9

**Comment by brianhlin** [comment]
@jdost321 I suggest that we abandon this PR and go with #149 : that way we can continue to have stable 3.6 EL7 factory images and a more cutting edge OSG 23 EL9 image

**Comment by jdost321** [comment]
sounds good I'll close this one.

**Pull request closed without merging**
