### PR TITLE
Add recommended production frontier cache size to container docs (SOFTWARE-5289)

### PR DESCRIPTION
**Pull request by jthiltges**
Barry recommends 50GB to 100 GB in [GGUS#158468](https://ggus.eu/index.php?mode=ticket_info&ticket_id=158468).

### CODE REVIEW

**Review by DrDaveD — APPROVED** [review]
This is reasonable, but doesn't it have implications on all the current installations?  Don't they have to make sure they have reserved enough disk space?  How will the word get out to all the current users?

Maybe there needs to be a check added to make sure there is enough free disk space just before starting squid.  I would run `/etc/init.d/frontier-squid cleancache` first to make sure the cache space has been cleaned first; otherwise the start command does that anyway, this would just make sure it is done before the free space check.

**Comment by jthiltges** [comment]
That's a good point on existing sites. It shouldn't be too bad to run a `df` on the cache directory to see how much space is available.

After the cleancache, maybe something like `min(80% free, SQUID_CACHE_DISK)` ?

**Comment by brianhlin** [comment]
>  How will the word get out to all the current users?

ATLAS is a big user of the container and they use the SLATE Helm chart which also defaults to 10GB. Fred assures me that all the Squids run this way have at least 50GB of cache.

We can otherwise make a release announcement for this (FYI @timtheisen )

**Comment by DrDaveD** [comment]
Come to think of it, frontier-squid itself also defaults to 10G, but the installation documentation strongly suggests that installers for production increase that value to a more appropriate amount.   That is another way to do this instead of increasing the default.   There are likely users of this container that just use it for testing so they don't need a larger amount (although on the other hand they're unlikely to actually fill up the cache either, depending on how much testing they do).  Also, by starting with a small default, it's more likely that an installer of a production system will be forced to make a conscious choice of how much to allocate; for example even 50G is a bit on the low end, so if somebody has a lot more space and they're forced to choose then they may choose a larger amount, but if they are never forced to choose they're likely to leave it at 50G when it would be better to be higher.  I'm not saying that it's necessarily a bad idea to increase the default for the container case, but it's not obviously a good idea either.

Having said all that, if we want to go ahead with increasing the default then I do think it would be good to add a df check for at least 20% more free than defined after cleancache, resulting in a crash with a clear message if it isn't available.

**Comment by jthiltges** [comment]
Hmm. I can certainly see the value in keeping the cache_dir setting consistent with upstream.

With a site-admin hat on--thinking about what would be least surprising--a service with defaults that are production-capable (if sub-optimal) would make life easier.

Perhaps this change, if folks want to make it, should start at the frontier-squid side? It's been 10GB for 11+ years, it seems. And both hardware and access patterns have changed in that time.

Maybe for now, we could instead add cache_dir recommendations directly in the [OSG squid docs](https://osg-htc.org/docs/data/frontier-squid/), and in the [docker image readme](https://github.com/opensciencegrid/images/blob/main/opensciencegrid/frontier-squid/README.md)?

**Comment by DrDaveD** [comment]
I don't want to change the frontier-squid default since I know there are still cases where 10G is the right choice, for example for testing or if somebody starts a squid on every worker node and leaves the cache in the default location under /var.

The OSG frontier-squid doc already just defers to the upstream installation documentation, and there making a choice for the cache size is very explicit.    It makes sense to update the [frontier-squid container docs](https://osg-htc.org/docs/data/run-frontier-squid-container/) and the docker image readme.

**Comment by jthiltges** [comment]
Do you have write access @DrDaveD, to re-review and merge?

**Review by DrDaveD — APPROVED** [review]

**Review by matyasselmeci — APPROVED** [review]

**Pull request merged**
